
namespace SharedServices.Objects
{
    public enum EnumActions
    {        
      
        EVENT_CREATE,
        EVENT_UPDATE,
        EVENT_CLOSE,
        EVENT_REOPEN,
        EVENT_CANCELED,
        NOTE_REGISTER,
        ASSISTANCE_CONTACT_ATTEMPT,
        ASSISTANCE_CASE_REVIEW,
        EVENT_PROVIDER_CONTACTED,
        EVENT_PROVIDER_CREATE,
        EVENT_PROVIDER_UPDATE,
        EVENT_PROVIDER_RESCHEDULE,
        EVENT_PROVIDER_RESOLVE,
        EVENT_PROVIDER_CANCELED,
        TRANSFER_TO_TMO,
        TRANSFER_TO_PROVIDER,
        TRANSFER_TO_ASSISTANCE_TEAM,
        EVENT_PHONECONSULTATION_CREATE,
        EVENT_PHONECONSULTATION_RESCHEDULE,
        EVENT_PHONECONSULTATION_ATTEMPT_FAIL,
        EVENT_PHONECONSULTATION_RESOLVE,
        EVENT_PHONECONSULTATION_CANCELED,
        GUARANTEE_PAYMENT_CREATE,
        GUARANTEE_PAYMENT_UPDATE,
    }
}
