namespace EventServices.Domain.Dto.Query;

public record ViewEventDetailsGetDto
(
    int Id,
    string CodeEvent,
    int IdClient,
    string CodeClient,
    string? Description,
    string Voucher,
    string PlanVoucher,
    string IssueBy,
    DateTime DateOfIssueVoucher,
    DateTime StartDateVoucher,
    DateTime EndDateVoucher,
    int MissingDays,
    string StatusVoucher,
    string DestinationVoucher,
    string TypeIdentification,
    string Identification,
    string Email,
    string Mobile,
    string Gender,
    string FullName,
    string Names,
    string LastNames,
    DateTime DateOfBirth,
    string CountryOfBirth,
    string EventType,
    int EventStatusId,
    string EventStatus,
    string? AssignedTo,
    DateTime EventStart,
    DateTime? EventEnd,
    decimal? ActualAmountUsd,
    string? Country,
    string? City,
    string? Address
    );